### ISSUE TITLE
regression bug in component config generation

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#1016]
After merging PR #968 secure aggregation fails in branch `feature/1002-fix-secagg-failure` either on nodes (`FB300: undetermined node error: int too big to convert`) or on researcher (decryption error message during aggregation).
* note: it **does not always fail** in the branch `feature/1016-fix-biprime-config-bug` due to the different encoding of secagg vectors, but yet the regression bug exists (using bad value of default biprime, which does not provide adequate security with secagg)

This is due to component configuration generation that does not include creating of default biprime in database when the configuration is auto-generated:

1. When we first generate a configuration with a

```
fedbiomed_run configuration create -c xxx
```

... then the configuration file created includes a registration for the default biprime biprime0 in the component's database.
Then launch fedbiomed_run => it works

2. when auto creating configuration file (eg `fedbiomed_run start`)
then the configuration file created does not include a registration of biprime0. It is later created when running a training round, but then calls the `SecaggContext._payload_create()` which creates a dummy entry with a random number (test code). => it fails

So the regression probably comes from new file generation that does not include creating default biprime in the component's database

**Comment by mvesin** [comment]
@srcansiz the regression comes from the modification of `fedbiomed_run` that previously generated a configuration with `fedbiomed_run configuration create` before launching a component.

If we don't want to have this in `fedbiomed_run`, we should execute the default biprime registration each time we generate a config file (in `fedbiomed.common.Config` ? )

**Comment by srcansiz** [comment]
> @srcansiz the regression comes from the modification of `fedbiomed_run` that previously generated a configuration with `fedbiomed_run configuration create` before launching a component.
> 
> If we don't want to have this in `fedbiomed_run`, we should execute the default biprime registration each time we generate a config file.
> 
> [EDIT] maybe in `NodeEnviron.set_environ()` and `ResearcherEnviron.set_environ()` ?

Hi @mvesin , 
Yes I agree, I am trying to move biprime registration into `config.generate` function instead of generating through CLI.
