### ISSUE TITLE
review internal class consistency tools for `Experiment`

### ISSUE THREAD

**Issue by sharkovsky** [fedbiomed/fedbiomed#1030]
- aggregator
- training data

**Comment by mvesin** [comment]
Review of `Experiment`: it may be nice to assess the `training_plan_approve(self, description)`.

Previous implementation was `training_plan_approval(self, training_plan, description, nodes)` which enabled requesting approval for a different training plan than the one active in the experiment. This may be nice to keep.

Even nicer might be to have `training_plan_approve()` as a class method, to be able to ask for training plan approval without intentiating an experiment (but maybe complicated/not possible to implement).

**Comment by mvesin** [comment]
Reminder: as discussed, elements that might be missing ( == None) to run an `Experiment`
- `self.__training_plan`
- `self._fds`

We could:
- have a function testing which elements are missing (see `develop` branch)
- call from info to print if experiment is ready to run (see `develop` branch)
- call from `run_once()` : replace test for `self._node_selection_strategy != None`)

**Comment by mvesin** [comment]
Update `Experiment.set_training_data`
