### ISSUE TITLE
[New issue]: Which communication protocol and serialization method is supported?

### ISSUE THREAD

**Issue by Rene36** [fedbiomed/fedbiomed#1055]
Dear FedBioMed Team,

I am currently writing a survey paper on Federated Computing. One part of it describes existing FL frameworks. Could you please let me know which communication protocol (e.g., gRPC, WebSocket, HTTP, GLOO) and serialization method (e.g., Pickle, JSON, Protobuf, FOBS) FedBioMed supports? I already saw in your documentation that you support gRPC, but maybe there is more.

Any help is highly appreciated.

**Comment by sharkovsky** [comment]
Hi @Rene36, 

thank you for your interest! 
As of Mars 2024, Fed-BioMed uses:
- gRPC for communication (exclusively)
- a custom serialization method based on [MessagePack](https://msgpack.org/index.html) with several extensions implemented by us (MessagePack is itself based on JSON)

Note that gRPC internally uses protobuf for serialization of the remote protocols, but I assume you meant serialization of the model weights and other related objects.
