### ISSUE TITLE
Small dysfunctions in User Guide

### ISSUE THREAD

**Issue by lchambon** [fedbiomed/fedbiomed#1068]
After reading the User Guide, here are some small dysfunctions spotted:

-  [x] In User Documentation/Getting Started/Basic Example, in the paragraph “Basic Full Example (for jupyter-notebook)”: the title “Multilayer Perceptron in Pytorch: model training loop (same example as previous one but transposed to Fed-BioMed)” should be replaced by “Multilayer Perceptron in Pytorch: model training loop” and the title “Multilayer Perceptron in Fed-BioMed with Pytorch: model training loop” may be replaced by “Multilayer Perceptron in Fed-BioMed with Pytorch: model training loop (same example as previous one but transposed to Fed-BioMed)”.

- [x] In User Documentation/User Guide/Researcher, the page “Configuring Researcher” does not work

- [x] In User Documentation/User Guide/Researcher/Training Data: in the paragraph just before “Conclusion” there is written “for example”, and there is no example.

- [x] In User Documentation/User Guide/Researcher/Experiment, in figure 2: should we change the “MQTT” communication by “gRPC” ?

- [x] In User Documentation/User Guide/Researcher/Aggregation, in paragraph “Fed-BioMed Aggregators”: the link “tutorial” does not work.

- [x] In User Documentation/User Guide/Optimization, the following links do not work: “its Optimization facility”, “declearn Optimizers documentation”, “declearn’s Optimizers documentation”, “Advanced Optimizers tutorial”, “the tutorial related to the use of declearn’s Optimizers”

**Comment by mvesin** [comment]
Fixed as part of #1170
