### ISSUE TITLE
Clean generated data during the end2end tests on the researcher side

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#1081]
- [ ] Create a new function (similar to clean_node_data) to remove researcher related files generated during end2end experiment.
- [ ] This function can be executed right after single test finished or all the tests in a test file is finished.

**Comment by ybouilla** [comment]
Files to remove for `Researcher`
- [ ] config files
- [ ] `Experiment` breakpoints
- [ ] Researcher's database
