### ISSUE TITLE
Building `gui` container fails because of missing `fedbiomed-node` environment

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#1091]
Running `./scripts/fedbiomed_vpn build gui` fails with:

```
- building 'gui' container
[+] Building 264.9s (23/23) FINISHED                                                                                                
...
 => [gui 18/19] RUN conda env update --file ./envs/vpn/conda/fedbiomed-gui.yaml &&  pip cache purge && conda clean -a -y     225.2s
 => ERROR [gui 19/19] RUN ./scripts/fedbiomed_run node gui data-folder /data config DUMMY install-only start                   1.4s
------
 > [gui 19/19] RUN ./scripts/fedbiomed_run node gui data-folder /data config DUMMY install-only start:
#0 1.161 
#0 1.161 EnvironmentNameNotFound: Could not find conda environment: fedbiomed-node
#0 1.161 You can list all discoverable environments with `conda info --envs`.
#0 1.161 
#0 1.161 
#0 1.330 Traceback (most recent call last):
#0 1.330   File "/fedbiomed/scripts/fedbiomed", line 8, in <module>
#0 1.330     from fedbiomed.common.cli import CommonCLI
#0 1.330   File "/fedbiomed/fedbiomed/common/cli.py", line 18, in <module>
#0 1.330     from fedbiomed.common.certificate_manager import CertificateManager
#0 1.330   File "/fedbiomed/fedbiomed/common/certificate_manager.py", line 9, in <module>
#0 1.330     from OpenSSL import crypto
#0 1.330 ModuleNotFoundError: No module named 'OpenSSL'

```

This is due to new CLI syntax `fedbiomed_run node gui` that treats this command as other `fedbiomed_run node` commands, and thus uses `fedbiomed-node` conda environment.

**Comment by srcansiz** [comment]
What I expect from GUI environment is to have all modules that Node has because it is the GUI of node component. Currently we have limited functionalities in the GUI for in the future this may change. For example, we may need this `OpenSSL` module to manage certificates. 

However, due to long installation time we tried keep GUI environment as minimum as possible but once we can manage to stack additional modules over existing fedbiomed environment this won't be problem.

**Comment by mvesin** [comment]
Thank you @srcansiz I will apply your recommandation:

> If you want to do simple fix you can just call fedbiomed_gui scripts instead of fedbiomed_run.

Regarding whether we want to have the full `fedbiomed-node` in `fedbiomed-gui`, this has deep implications - so we probably need to discuss before going that direction. Nice if we can avoid it for this fix ...
