### ISSUE TITLE
SecAgg: fixing and adding unit tests

### ISSUE THREAD

**Issue by ybouilla** [fedbiomed/fedbiomed#1141]
Part of #942 

This issue details the remaining work for fixing and adding unit tests before being able to merge the LOM secure aggregation branch into `develop`

**Broken unit tests to be fixed**
1. **Classes that will not change while working on secure aggregation**
- [x] `Federated_workflow`
- [x] `Job`
- [x] `TrainingPlanSecurityManager`
- [x] `Messages`
- [ ] 
2. **Classes that may change while working on secure aggregation**
- [x] `Node`
- [x] `Round`
- [x] transport `NodeAgent`
- [x] `Server`
**Unit tests that need to be created and added**
*units tests about secagg*

To track advancement on unit tests: `feature/942-unit-tests`

**Comment by srcansiz** [comment]
Hi @ybouilla,
You don't need to fixi tests`test_secure_aggregation.py`. I am currently working on this test file to check the implementation is current, and it also fixes the broken unittests. 

Thanks.
