### ISSUE TITLE
Solve broken Joye-Libert e2e tests

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#1152]
While Joye-Libert secure aggregation work correctly in manual experiment execution it fails in e2e tests. This is not a bug but a glitch in e2e machinery. The error comes from `FDH.H` function:

```python 
        counter = 1
        result = b""

        while True:
            while True:
                h = hashlib.sha256()
                h.update(
                    int(t).to_bytes(self.bits_size // 2, "big") +
                    counter.to_bytes(1, "big")
                )
                result += h.digest()
                counter += 1
                if len(result) < (self.bits_size // 8):
                    break

            r = mpz(int.from_bytes(result[-self.bits_size:], "big"))

            if gcd(r, self._n_modules) == 1:
                break

        return r
```

`counter` value goes over `256` result `int to big to convert` while executing `counter.to_bytes(1, "big")`, in normal case counter value usually stay between 1 and 10 max. 

This problem is introduced in the commit `487ee64014a0a04dcc588f2e5800bb3777ac5ae2` where a singleton `db.Table` is implemented. Using non-singleton `Table` class fixed the issue. The reason of this issue is not clear but it shows that  shows that e2e test machinery not resilient to singleton implementation. The nodes are started in background processes this avoids have problem regarding singleton on the node layer, however, there  may be some problem on the researcher side.

**Comment by ybouilla** [comment]
Hi Sergen, thanks for investigating.
I think the above code could gain robustness: we are doing infinte loops (`while True:`), but can we loop over the number of bit instead (before reaching `256` and leading to a Overflow error

**Comment by ybouilla** [comment]
I tried to run only the first end-to-end test `test_01_secagg_joye_libert_pytorch_experiment_basic` 

I got a different error: 
```

        if len(validation) != 1 or not math.isclose(validation[0], self._secagg_random, abs_tol=0.03):
>           raise FedbiomedSecureAggregationError(
                f"{ErrorNumbers.FB417.value}: Aggregation has failed due to incorrect decryption."
            )
E           fedbiomed.common.exceptions.FedbiomedSecureAggregationError: FB417: secure aggregation error: Aggregation has failed due to incorrect decryption.
```

**Comment by srcansiz** [comment]
> I tried to run only the first end-to-end test `test_01_secagg_joye_libert_pytorch_experiment_basic`
> 
> I got a different error:
> 
> ```
> 
>         if len(validation) != 1 or not math.isclose(validation[0], self._secagg_random, abs_tol=0.03):
> >           raise FedbiomedSecureAggregationError(
>                 f"{ErrorNumbers.FB417.value}: Aggregation has failed due to incorrect decryption."
>             )
> E           fedbiomed.common.exceptions.FedbiomedSecureAggregationError: FB417: secure aggregation error: Aggregation has failed due to incorrect decryption.
> ```

Hi @ybouilla,
Thank you for testing the issue. I am going to run again this test and compare the result that I got before, something may be changed since the issue created.
