### ISSUE TITLE
Small issues regarding website

### ISSUE THREAD

**Issue by ybouilla** [fedbiomed/fedbiomed#1153]
There are a few issues on the [Fed-BioMed website](https://fedbiomed.org/), that can be improved:

- ~~[ ] On the footer there is written `Fed-BioMed @ 2022`~~ Not really needed eg https://nexb.com/do-you-really-need-to-update-the-copyright-each-new-year/
- [x]  in the section **user-support**, `issue archive` link redirects to stale branches of github. It should redirect to `https://github.com/fedbiomed/fedbiomed/issues`

**Comment by LSoutherton** [comment]
Hi, I would love to take a look at these issues for you. Would you be able to provide a link to where you want the 'issue archive' link to take you?

**Comment by ybouilla** [comment]
Hi, thanks for your help and your interest in the project. I have just updated the issue, feel free to fork the project from develop and propose your changes. Thanks!

**Comment by mvesin** [comment]
Hi @LSoutherton 

Do you need any more help or information about this issue ?

Thank you again for your interest in the project
