### ISSUE TITLE
Create message types for additive secret sharing

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#1184]
This is a task to create necessary message types that are going to be used while  transferring information among nodes and between nodes and researcher. 

```
# Between nodes
AdditiveSShareRequest()

# Between nodes
AdditiveSShareReply()


AdditiveSSSetupRequest : from researcher to all nodes
AdditiveSSSetupReply : from nodes to researcher that contians sum of shares that are calculated local on the node side (ServeyKeyShare)
```

**Comment by ybouilla** [comment]
> AdditiveSSSetupRequest : from researcher to all nodes
> AdditiveSSSetupReply : from nodes to researcher that contians sum of shares that are calculated local on the node side (ServeyKeyShare)


For those messages, I propose to use the current `SecaggRequest` and `SecaggReply` to make them more generic
