### ISSUE TITLE
Researcher notebook requires authentication

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#1194]
Recently appeared regression issue:
- when launching `./scripts/fedbiomed_run researcher start` then open a notebook
- "token or password" is required each time we click on a notebook or directory

It is suspected to come with recent pip/conda dependency package version upgrade, and was triggered when testing full rebuild of the researcher environment.

**Comment by ybouilla** [comment]
If one wants to disable security, one can run `jupyter-notebook --NotebookApp.password="" --NotebookApp.token=""
`.
But is it really a good idea to disable security? I would say that it is case dependent, and for security reasons we may want to keep security through token or password

**Comment by mvesin** [comment]
@ybouilla tested successfully the fix on my laptop (Linux Fedora 38):
- in `dev` mode
- in `vpn` mode
  * accessing `https://localhost:8888`
  * mounting a ssh tunnel (`ssh -L 1234:localhost:8888 user@localhost`) then `https://localhost:1234`

So IMO it's working fine. Are you sure you properly restarted from clean env when testing ? eg:
- `fedbiomed_environment clean`
- `fedbiomed_vpn clean image`
- (just to be cautious ...) `rm -rf ~/.jupyter`
- `conda remove -y -n fedbiomed-researcher --all` then rebuild conda
- then rebuild researcher container and run it
