### ISSUE TITLE
end to end tests

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#181]
In GitLab by @j-l-s on Dec 9, 2021, 15:59

Provide a way to automatize integration tests:
- [x] generalize the getting-started.py script to launch more than one test (done in !169)
- [x] create a nightly task on ci.inria.fr to test all scripts/notebooks provided by fedbiomed repo and gitlabpages repo
  - [x] nightly task created: fedbiomed-integration-linux (done in !169)
- [x] create a nightlty task on ci.inria.fr to test a VPN setup and training
- [x] Add multiple node support for integration tests. (done in !169)

Priority: fix existing integration tests
- [ ] fix #479

**Comment by ErwanDemairy** [comment]
solved with #931 , among others.
