### ISSUE TITLE
investigate new website for communication purpose

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#222]
In GitLab by @mvesin on Feb 25, 2022, 09:29

Investigate how to provide a new website, more "multimedia" oriented

- separate the gitlabpages (dedicated to the documentation/tutorial) from the "communication part" 
- need a Domain Name
- which technology ? (CMS, homemade,..)
- which type of hosting ?  
- which features (multimedia aspects, user interaction)
- technical aspects (SSL certificate, log access/analysis)
- juridic aspects (RGPD, logs,...)
- maintenance (hardware, plateform, software, content)
- cost (initial, recurrent)

First tasks:
- [ ] discussion with people from other project (get feedback)
- [ ] write requirements
- [ ] evaluate costs

**Comment by mvesin** [comment]
obsoleted by fedbiomed.org
