### ISSUE TITLE
Improve Code Quality -> Coding Convention

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#274]
This issue is a milestone from SP15. It is about deciding the actions that should be taken to improve code quality. Coding style and folder/file-name convention.

- [ ] Agree on coding rules: Add/Extend/Elaborate coding rules
- [ ] Provide check rules (flake8 configurations or scripts .etc. )
- [ ] Coherent naming of the files (eg: `_fedbiosklearn.py`, `_torchnn.py`) and directory tree organization
- [ ] How to import fedbiomed module -> `__init__.py`
- [ ] Rewrite definition of done (DoD)
- [ ] Apply the rules to the existing code

**Comment by mvesin** [comment]
obsolete, see DoD and CODING.md for current version
