### ISSUE TITLE
Provide an easy and robust way to define optimizer for PyTorch from researcher side

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#283]
In the current implementation of optimizer management; researcher can define optimizer in the `__init__` of training plan class. However, this implementation does not allow to pass optimizer arguments (e.g `lr`) to the optimizer which is defined in the `__init__` because it is already built. Therefore, implementation of optimizer should flexible where researcher can define an optimizer and manage its parameters from one round to other (plus, researcher shoudlbe enable to define multiple arguments not only `lr`). 

----------------------------------
**First proposal: Let end-user to define optimizer as `Callable` in their training plan**  

```
class MyTrainingPlan(TorchTrainingPlna):
    def __init__(self, model_arguments = {}):
        
        self.optimizer = torch.optim.Adam

```

and build optimizer in the trianing routine 

```class TorchTrainingPlan:

   .....

   def training_routine( optimizer_arguments )
 
       #.....
       self.optimizer = self.optimizer(self.model.parameters(), **optimizer_arguments)

```

----------------------------
 
**Second Option: Let end-user to declare optimizer in the training arguments**

This is more flexible then the first option. This implementation will allow researcher to define different optimizer for different nodes as well as researcher will able to change optimizer from one round to other easily as well as .  

Enumeration class for PyTorch optimizers:

```python 
class PyTorchOptimizers(Enum):
   ADAM = torch.optim.Adam 
   SGD  = torch.optim.SGD
```

Let researcher define optimizer: 

```python
optimizer = {
    "arguments" : {
        "lr" : 0.05, 
        ".." : ..
    }, 
    "optimizer" : PyTorchOptimizers.ADAM
}

training_args = TrainingArguments({
    "optimizer" : optimizer
})

exp = Experiment(training_args = training_args)

```
In the training routine, build the optimizer: 

```python
def training_routine(optimizer, ...):

    self.optimizer = optimizer["optimizer"](self.model.parameters(), **optimizer["arguments"])

```

**Comment by ybouilla** [comment]
Closing this issue because already completed with the introduction of declearn optimizer #735  and Node state saving facility #863
