### ISSUE TITLE
Documentation - Add More Tutorials/Docs

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#359]
In GitLab by @ErwanDemairy on Sep 16, 2022, 16:10

(was : SP16 - ITEM 04)
**The goal is to gain more visibility on the project, gather new contributors, disseminate our work** 

Focus on the real purpose of fedbiomed, what it makes Fedbiomed unique -> open source and interactive FL framework for healthcare

- [ ] Conclude first on documentation skeleton
- [ ] Find a way to provide datasets, ask for permission if necessary
- [ ] Reorganize existing tutorials based on what is decided on skeleton 
- [ ] Propose list of new tutorials 
- [ ] Start writing proposed tutorials

**Comment by mvesin** [comment]
obsoleted by new versions of documentation
