### ISSUE TITLE
Unit tests hang forever if MQTT process is not running

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#390]
In GitLab by @sharkovsky on Oct 11, 2022, 11:34

If the MQTT process (the docker container or whatever else) is not running, the unit tests hang forever in the following call stack:
`TestMessagingResearcher.setUpClass` -> `Messaging.start()`, and similarly for `TestMessagingNode`

Specifically, they hang in the loop at line 219 of `messaging.py`
```python
while not self._is_connected:
    pass
```

I believe the unit tests should be able to run even when the mqtt broker is not running, and we should try to mock the class.

**Comment by sharkovsky** [comment]
This is now fixed, at least in my experience
