### ISSUE TITLE
Researchers should not be required to import un-needed dependencies in their notebooks

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#404]
In GitLab by @sharkovsky on Nov 14, 2022, 15:31

Currently, researchers must import all dependencies that are used by the `init_model` and `init_optimizer` functions in their notebooks, because on the researcher side we execute `training_plan.post_init` when setting up an Experiment. 

This is confusing, because one would think that those dependencies are really only needed by the node, not on the researcher side.

**Comment by sharkovsky** [comment]
Fixed by #870
