### ISSUE TITLE
Use Python `argparser` to parse arguments of CLI commands instead of bash script

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#434]
Node CLI uses bash script to parse CLI commands, and executes `node.cli` with corresponding option. This approach duplicates options and parsing in both bash and `node.cli`. For example: `fedbiomed_run node add` parses `add` command and executes `fedbiomed.node.cli -a | --add`. So `add` command is parsed both in bash and python. 

Since the Fed-BioMed CLI is more mature in having more options than before, the CLI module needs to be refactored for simplicity's sake. 

1 - Option that are given after `fedbiomed_run node [...]` can passed directy to the `fedbiomed.cli`.  

2 - Instead of using `if` and `else` in `fedbiomed.node.cli` use `subparsers`. here is an example use of subparser
   
```
parser = argparse.ArgumentParser()
subparsers = parse.add_subparsers()


database_add = subparsers.add_parser("add", help="Help string")
database_add.set_defaults(func=add_dataset)

def add_dataset(args):
   # Access extra arguments through `args`
   pass

```

**Comment by mvesin** [comment]
- does not match the requirement of backward compatibility
- does not match `./scripts/fedbiomed_run node --help`

```
$ ./scripts/fedbiomed_run node configuration create

# Using configuration file: node_config.ini #
usage: fedbiomed_run [-h] [--config [CONFIG]] {start,dataset,training-plan,gui,certificate} ...
fedbiomed_run: error: argument {start,dataset,training-plan,gui,certificate}: invalid choice: 'configuration' (choose from 'start', 'dataset', 'training-plan', 'gui', 'certificate')
```

**Comment by mvesin** [comment]
Failure with:

```
$ ./scripts/fedbiomed_run node add

DEPRECATION WARNING!:
fedbiomed_run node add | --add | -a is deprecated. This command will be removed in the future releases. Please use fedbiomed_run node --config [CONFIG_FILE] dataset add

# Using configuration file:  #
Traceback (most recent call last):
  File "/home/mvesin/GIT/fedbiomed/fedbiomed/fedbiomed/common/config.py", line 58, in __init__
    self.generate()
  File "/home/mvesin/GIT/fedbiomed/fedbiomed/fedbiomed/common/config.py", line 179, in generate
    return self.write()
  File "/home/mvesin/GIT/fedbiomed/fedbiomed/fedbiomed/common/config.py", line 105, in write
    with open(self.path, 'w') as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/mvesin/GIT/fedbiomed/fedbiomed/etc/'

# Using configuration file: node_config.ini #
usage: fedbiomed_run [-h] [--config [CONFIG]] {start,dataset,training-plan,gui,certificate} ...
fedbiomed_run: error: argument {start,dataset,training-plan,gui,certificate}: invalid choice: 'add' (choose from 'start', 'dataset', 'training-plan', 'gui', 'certificate')
```

**Comment by mvesin** [comment]
Documentation (`./docs`) and notebooks (`./notebooks`) and code ... need update. They still contain many occurences of old syntax:
- `fedbiomed_run node start|list|config|certificate|training_plan|etc...`
- `fedbiomed_run researcher start|configuration|certificate|etc...`

**Comment by mvesin** [comment]
New cli parameter added is `fedbiomed_run node dataset xxx`.

Wouldn't it be more coherent with new syntax to introduce: `fedbiomed_run node --dataset xxx`

**Comment by mvesin** [comment]
Did you test new CLI with building containers & running containers (locally on laptop) using https://fedbiomed.org/latest/user-guide/deployment/deployment-vpn/ ?

This would be nice for non regression regarding multiple changes.
