### ISSUE TITLE
`declearn` integration into `Fed-BioMed`: decide how to import code

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#453]
In GitLab by @ybouilla on Jan 9, 2023, 17:09

Regarding `declearn` `Optimizer` integration, we need to decide how to integrate `declearn` work into FedBioMed:
1. copying `declearn` code into FedBioMed
2. importing `declearn` as a third party package

## 1. Pros and cons of copying `declearn` package into fedbiomed

**Pros**:
- `declearn` api may diverge in the future, interoperability with FedBioMed may not be always granted
- we can fine tune `Optimizers` to adapt to fedbiomed

**Cons**:
- we also have to provide unit tests  for those `Optimizers` (unit test code can be copied from `declearn`)

## 2. Pros and cons of importing `declearn` package
**Pros**: 
- `declearn` team will deal with FedBioMed interoperability 
- `declearn` team will take care of testing/bug patching 

**Cons**: 
- regarding `Optimizer` class, there might be some connection with other `declearn` modules (this will be fixed by `declearn` team in the future)
- `declearn` will come additional packages and code, that will make fedbiomed even heavier (this will be fixed by `declearn` team in the future)

**Comment by ybouilla** [comment]
closing because redundant with #735
