### ISSUE TITLE
Generate user key shares in accordance with the biprime bit length for the current experiment

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#488]
The current implementation of key generation is done using hard-coded bit length as `2048`. The bit length should be dynamic based on the bit length of the biprime value. Currently, it is not a problem since a single biprime is stored statically. This guarantees that the bit-length is not going to change from one experiment to another.  However, once the issue #440 is completed, the bit length of key-share should be set based on the biprime created for an (or multiple) experiment. 

1 - Biprime context should be instantiated before the secure aggregation server-key generation request.  
2 - The bit-lenth should be attached to the secagg request so the nodes can use this bit-length for the key generation.  
3 - For the breakpoints, if the user key (secagg entry) is deleted on node side a new key generation should be done using the newest biprime.

**Comment by mvesin** [comment]
No plan to extend Joye-Libert secagg, now concentrating on FLAMINGO
