### ISSUE TITLE
Mismatch between parameters saved by job and loaded by node

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#513]
In GitLab by @sharkovsky on Apr 18, 2023, 15:50

I keep getting the following errors
```
'TorchModel.set_weights' received inputs that did not cover allmodel parameters; missing weights: ['unet.model.0.conv.unit0.adn.N.running_mean', ...
```

A little bit of investigation has led me to the following point
1. the `model.get_weights` function calls `named_parameters`
2. but the `model.set_weights` function uses `load_state_dict`

Indeed, those missing weights in the error message are present in the state dict, but are not named parameters. Furthermore, using `state_dict.items()` instead of `named_parameters` in `get_weights` solves the issue.

**Comment by sharkovsky** [comment]
Fixed by #746
