### ISSUE TITLE
work on deployability

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#514]
In GitLab by @ErwanDemairy on Apr 18, 2023, 15:51

- ~~[ ] estimated 5 m.d update or add CI slaves (3)~~
- ~~[ ] estimated 9 m.d backward compatibility and/or version assessment, (optionally: update package versions). See milestone.~~ done, other issue

**Comment by mvesin** [comment]
Not a specific issue, contained in #531 #532 #533 + #506 + #448
