### ISSUE TITLE
explore and discuss usage scenario and architecture evolution plans

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#515]
In GitLab by @ErwanDemairy on Apr 18, 2023, 15:54

(communications/MQTT/HTTP, detaching researcher from the server, securing communications, crypto material management): design coherent mid-term plan => create new issue and assign a few days of work (timebox  5 m.d split between core dev team during sprint)

**Comment by mvesin** [comment]
[Fed-BioMed scenarios and architecture.pdf](https://github.com/fedbiomed/fedbiomed/files/11984269/Fed-BioMed.scenarios.and.architecture.pdf)
