### ISSUE TITLE
VectorEncoding fix

### ISSUE THREAD

**Issue by rtaiello** [fedbiomed/fedbiomed#789]
### Dear user, welcome to the Fed-BioMed project ! We will get back to you as soon as possible.

A bug has been found and fixed here: https://github.com/MohamadMansouri/fault-tolerant-secure-agg/blob/main/ftsa/protocols/buildingblocks/VectorEncoding.py, it should be updated https://github.com/fedbiomed/fedbiomed/blob/e80c93b4fc3c8cef36e00a15adadf8092d365a18/fedbiomed/common/secagg/_jls.py#L172 accordingly.

**Comment by srcansiz** [comment]
Hi @rtaiello, 

Thanks for reporting this bug. Could you please specify exactly which that bug was. Because, we modified  `VES` API. The calculation is the same but the implementation is little bit different.

**Comment by srcansiz** [comment]
Hi @rtaiello, 

Could you please explain what are the consequences of this bug, is it related to the security or the way it is encoded now (without `add_ops + 1`)  causes information loss?

**Comment by rtaiello** [comment]
Hi @srcansiz,

It's an overflow of the integer which causes the msb of an element in the vector to be added to the lsb of the next element in the vector.

It happens in edge cases, for example: 
for some values, some vector elements are shifted by one. So if the value of a client is the maximum ptxt  size (i.e., ptxt size=2**16) and a client has a value of 2**16, an overflow can happen. 

**I'm working to replicate this bug.**
