### ISSUE TITLE
Insecure validation sec agg

### ISSUE THREAD

**Issue by rtaiello** [fedbiomed/fedbiomed#804]
After a discussion with @srcansiz, we realized that the validation of the aggregation through the encryption of random values, also known to the aggregator can be an information leakage.
There might be several approaches, depending on the assumptions that we can make, here the list of a couple of possibilities:
- https://openreview.net/pdf?id=WA7I-Fm4tmP
- https://eprint.iacr.org/2015/562

**Comment by mvesin** [comment]
Implementing a change to make secagg validation:
- enabled by default in `development` mode
- disabled by default in `vpn` container mode

- [ ] implement in library as described below
- [ ] test in VPN/container mode
- [ ] adapt unit tests
- [ ] adapt documentation

Implemented solution:
1. when generating a node/researcher config file, create a param `security > secagg_insecure_validation`, boolean that defaults to `True`
2. when launching node/researcher or creating config file, can overwrite this value with `SECAGG_INSECURE_VALIDATION` environment variable. If not overwriting: use value from file.
3. in VPN/container mode documentation (later: scripts) execute commands that *disable* validation in config file
4. at run time
    * if validation is disabled on researcher, then it sends a `None` value for `secagg_random`. If validation is enabled then it sends a float (unchanged)
    * if validation is disabled on node and received `secagg_random` is not `None` then node sends an error to the researcher and does not train
    * if node receives a `secagg_random` which is `None`, then its reply has `encryption_factors` to `None`
    * if researcher receives a node reply with `encryption_factor` to `None` while it sent a float `secagg_random`, then it fails
