### ISSUE TITLE
Github actions-runner in macos slave stops after user logs out from ssh session

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#825]
The service for actions-runner stop afters the user that starts the service logs out. Service restarts if user logs in again. 

Here are several options that are tested but didn't work

- Launching service as root and keeping `,plist` file in `LaunchDaemons` directory
- Launching `run.sh` using `nohup`  -> `nohup run.sh & disown`

**Comment by mvesin** [comment]
Solved.

This was due to the Mac going to sleep when idle. As the agent is running on the Mac, the wake on lan flag is not enough (the Mac is the client, not the server).
Disabled the Mac going to sleep with: https://osxdaily.com/2023/01/02/how-prevent-mac-sleeping-when-display-is-off/
