### ISSUE TITLE
Implement "version 1" of node state

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#836]
20 m.d Implement "version 1" of node state on node side and server side:
- handle on node side
- handle on server side
- add state_id to messages
- save in breakpoint

Depends on:
  * #811 design node state

Needed by:
  * #837 Protect auxiliary variables with secagg

**Comment by ybouilla** [comment]
**Note about the database**:

FOr now we will use TinyDB as database, but we may want to switch to a datavase that offers more performances

such database(s) will  have to handle:
- save images / paths (should we use a document oriented database)
- state of a model/optimizer (pure sql  for performance)
- should we encrypt database?

**Comment by ybouilla** [comment]
I have noticed lags when database have certain number of entries:  I assumed it was due to  tinydb requests from NodeAgentManager taking time, but it needs more investigation (eg though profiler)
