### ISSUE TITLE
False positive in `check_data_quality` function prevents me from running experiment

### ISSUE THREAD

**Issue by sharkovsky** [fedbiomed/fedbiomed#849]
The `check_data_quality` function prevents me from running an experiment because of a mismatch in data types, even though as a researcher I am aware of this and I can easily fix it in the `training_data` function.

1) Due to the internal logic of `pandas`, the data types for a csv dataset **at the time of adding the dataset to the node** can be interpreted differently on different nodes (example: a column with only integers has int type, but the same column on another node with integers and NaN values becomes float)
2) Afterward, as a researcher when I build the experiment, I get an error because the data types are not consistent among nodes
3) This is not a real issue, because as a researcher I can easily fix the inconsistencies inside the `training_data` function. But I cannot change the way the dataset was loaded on the node (and therefore I am stuck with the default dtype logic of pandas)

This prevents me from running the experiment, even though it shouldn't.

**Comment by mvesin** [comment]
This issue is related to #424

**Comment by sharkovsky** [comment]
Fixed by #866
