### ISSUE TITLE
Fix deprecated notebook import

### ISSUE THREAD

**Issue by ybouilla** [fedbiomed/fedbiomed#885]
In the current version of Fed-BioMed, jupyter-notebook display has changed to a minimal version of notebook. This might be due to import of jupyter-notebook, which is now deprectated. One should indeed load jupyter-lab instead.

**Proposal**: replace jupyter-notebook import with jupyterlab

**Comment by mvesin** [comment]
Fixed in #931 by @ErwanDemairy
