### ISSUE TITLE
Node out of memory because of testing batch size

### ISSUE THREAD

**Issue by sharkovsky** [fedbiomed/fedbiomed#893]
Our current implementation for both [torch](https://github.com/fedbiomed/fedbiomed/blob/6c568b892e8222e04d15c23e39a331ab028cc2f9/fedbiomed/common/data/_torch_data_manager.py#L128) and [sklearn](https://github.com/fedbiomed/fedbiomed/blob/6c568b892e8222e04d15c23e39a331ab028cc2f9/fedbiomed/common/data/_sklearn_data_manager.py#L356) sets the batch size of the testing loader to be equal to the full testing dataset. 

This leads to an out-of-memory problem when the data types are too large (e.g. in the FeTS dataset, where each image has shape [128,128,128] and there are 4 modalities) and/or when the testing dataset is too large. 

Two possible solutions would be:
1) always set testing batch size equal to 1
2) allow user to set testing batch size through `loader_arguments`

This issue is related to #765, but is different from it because the problem described here (i.e. the issue with batch size) would still be relevant even if we fixed #765.

**Comment by ybouilla** [comment]
Hey Francesco, thanks for creating the issue. I will be working on option 2, since i guess batch size is something that user may want to change

**Comment by ybouilla** [comment]
How would you call testing batch size through `loader_arguments`? would `testing_batch_size` be ok?

**Comment by sharkovsky** [comment]
yeah that's ok. 
Or to be even more consistent `test_batch_size`, which follows `test_ratio`, `test_metric`, etc..

**Comment by ybouilla** [comment]
The introduction of such batch_size arise a few issues: 
one of them is what error to display: should we display only average of all errors computed over all batch sizes?

**Comment by ybouilla** [comment]
WIth the team we decided the following:

- we display  error for each batch size on the tensorboard plot  (we dont do the mean or something similar)
- `test_batch_size` will belong to the `training_args`

advancements are made on the following branch: #feature/893-testing-batch-size

**Comment by ybouilla** [comment]
I have done first  experiment on one Node with 2 rounds , 600 batches each, 
![image](https://github.com/fedbiomed/fedbiomed/assets/114240274/2b7a33fd-9d89-4f81-9cbe-ad06f7ae6e01)

Is this display ok ?

**Comment by ybouilla** [comment]
Also, what should be the default behaviour? 
1. disable testing_batch_size as default;
2. or set testing_batch_size to a specific value?

**Comment by ybouilla** [comment]
```
2024-02-21 16:55:41,224 fedbiomed INFO - VALIDATION ON GLOBAL UPDATES 
					 NODE_ID: NODE_8bd409a0-4282-4e33-b7a3-8e03aea586b9 
					 Round 1 | Iteration: 46/600 (8%) | Samples: 460/6000
 					 F1_SCORE: 0.018182 
					 ---------
```

**Comment by ybouilla** [comment]
After discussion with the team, this is what we agreed:
- default would be a `testing_batch_size= default training_batch_size`
- to disable `testing_batch_size`, one should enter `testing_batch_size=0` or  `testing_batch_size=None`
- both logs and tensorboard displays look ok
- implement `log_over_batch` for testing too, in order to display limited number of logs when doing testing
- should we re write the error message when a `OutOfMemory` error triggers while doing testing ? (eg `Node out of Memory, please consider using `testing_batch_size`)

**Comment by ybouilla** [comment]
The specific case `test_batch_size=1` has been classified as a bug, and is detailed in the issue #1013
