### ISSUE TITLE
refactor `Experiment` to have a Base shared between Experiment and FedAnalytics + refactor `Job` 

### ISSUE THREAD

**Issue by sharkovsky** [fedbiomed/fedbiomed#896]
Initial [proposal slides](https://docs.google.com/presentation/d/1Mz_0ICu6bhvK9J730B4f_KuqgYk6zvCBelNItXSRmV4/edit?usp=sharing)

See also PR #943 for additional description on the design choices

Here is a checklist of the tasks that still need to be done
- [x] #1031
- [x] Review Job (full hierarchy) implementation
- [x] #1032
- [x] #1010
- [x] Fix #1003 
- [x] #1028
- [x] #1029
- [x] #1030
- [x] #944
- [x] #1022
- [x] #1011
- [x] #1048
- [x] #1049
- [x] fix cleaning of temporary dirs created at training on node side (no issue)
- [x] #1033
- [x] #1042
- [x] #1012
- [x] #1041
- [x] [MV] cross check code for functions inconsistencies
   *  clean code from unused code/functions
   * update/remove references to refactored methods that changed signature or were removed
- [x] [MV] PEP8 code style (fix style, remove unused imports, ...)
- [x] [YB] review and manual testing of notebooks, including SecAgg
  * as part of tutorials/notebooks review in #1042
  * [SC] review of security tutorialx
  * [MV] review of scikit-learn tutorials & notebooks
- [x] test building containers + run some notebooks (101, secagg)
- [ ] merge develop
- [ ] ~Review potential interactions with work on declearn secure aggregation aux variables~
- [x] #1023

## Collaboration workflow

For reviews, suggestion, or small changes, you may modify the feature branch directly. 
For bigger changes, please create a branch from [the feature branch](https://github.com/fedbiomed/fedbiomed/pull/943) and create a merge request.

@sharkovsky in charge of keeping in sync with develop

**Comment by sharkovsky** [comment]
## Dev Discussion 2023-10-26

Most of the discussion was concentrated on `Job`.

### GRPC

GRPC also refactored `Job`. Therefore we need to base our design (and implementation!) on the grpc branch. 

### Job life-cycle

Many points were raised about the life-cycle of `Job`.
In the current implementation, a Job object is created at the beginning of Experiment, and it dies with Experiment. 
In the initial refactor proposal, a new Job object would be created for every new interaction between the experiment and the remote nodes. 
This proposal may not be ideal because:
- potential performance cost (creating objects means CPU cycles overhead as well as more memory footprint)
- software design, since there is really no data that should persist within this short life-cycle, thus making an object redundant

So we transitioned to a "Controller" approach, where a long-lived `Job` is created at the beginning of Experiment, but it is a very lightweight object **whose state does not include anything in common with Experiment**. The only "state" allowed for Job are objects that belong to lower layers, such as in particular `Requests`.

### (Abstract) interface design

The base `Job` class should have an abstract `create` and `execute` method. 
`create` is used to generate the corresponding `*Request` message (e.g. `TrainRequest`), while `execute` is used to actually send the message and interact with the `Requests` class. 

### Attention points while refactoring

We should pay close attention to the following points while refactoring Job:
- the life-cycle of job members (in particular Requests and training plan)
- shifting from job id to experiment id (addendum: this might be mitigate by the current design of having a long-lived lightweight Job)
- extend Job refactoring to `SearchJob`, `ListJob`, and possibly others

**Comment by ybouilla** [comment]
After discussion with Francesco, we think that `Node` state facility should be instantiated in the `Job` class, even if we are doing Federated Analytics

**Comment by sharkovsky** [comment]
> After discussion with Francesco, we think that `Node` state facility should be instantiated in the `Job` class, even if we are doing Federated Analytics.

After a second discussion, we decided to have it as a member of `Experiment` instead, since it is a persistent entity.

**Comment by sharkovsky** [comment]
Here is a checklist of the tasks that still need to be done
- [ ] Review the API for interacting with model weights
- [ ] Fix #1003 
- [ ] Improve code coverage (write unit tests)
- [ ] make `save_aggregated_params` a public method
- [ ] review and manual testing of notebooks, including SecAgg
