### ISSUE TITLE
SecAgg bugs due to reverse_quantizatin and node secret key length.

### ISSUE THREAD

**Issue by rtaiello** [fedbiomed/fedbiomed#898]
The actual quantization functions, don't allow to compute SecAgg with more than 2 users.

**Comment by mvesin** [comment]
hi @rtaiello did you really intend to close this issue (while it's `doing`) ?

**Comment by rtaiello** [comment]
Hey @mvesin I found this bug when I was using separately the function `quantize` 
I tested it and apparently the bug is in `reverse_quantize`https://github.com/fedbiomed/fedbiomed/blob/f1438eddec872b1eb5601ac41c487de64a9ab0bb/fedbiomed/common/secagg/_jls.py#L95
I found a fix, which is now working with 3 nodes, but not with 4, I'm working to understand it.

**Comment by rtaiello** [comment]
Hey @mvesin, @srcansiz.

There were two bugs in the code. The first bug was related to the `reverse_quantize` function, which was originally designed to work with just two nodes. I've now provided the corrected version of this function. It might be a good idea to include some local tests for it, which should be independent of the secure aggregation process.

Additionally, there was another issue in the code. The code was calculating the average of the aggregated parameters directly over the quantized values, which is not an optimal approach. To improve this, I now first reverse-quantize the summed parameters and then calculate the average.

The second bug is more complex and was related to a feature that wasn't considered when I initially provided the specifications for the secure aggregation protocol. The issue here is related to potential overflow in the generation of the server key, which should be limited to a maximum of 2048 bits.

The problem arises from the following line in the code: https://github.com/fedbiomed/fedbiomed/blob/f1438eddec872b1eb5601ac41c487de64a9ab0bb/scripts/fedbiomed_mpc#L339. This line generates a random node privacy key, which could have a length of 2048 bits. The problem occurs when we have multiple nodes; the number of bits required for the server key could become 2048 + log_2(n), where 'n' is the number of nodes.

To address this issue, there are a few potential solutions:

1. Increase the common modulus 'N' to a larger value, which depends on the number of nodes. This solution it's challenging.

2. Have the nodes generate a key where the number of bits is dependent on the number of nodes. If this information is available, each node could set its key length as `--n_len 2048 - log_2(n)` to ensure compatibility.

3. Implement a hard-coded solution where you tolerate a maximum number of nodes. For instance, you could set `--n_len` to 2040, which means you can tolerate up to 256 nodes.

For the moment I implemented 3. https://github.com/fedbiomed/fedbiomed/blob/7fdf9d496fad0b45defe2e45b0188bc55d0ccd8d/scripts/fedbiomed_mpc#L339

Feel free to discuss whenever you want.
