### ISSUE TITLE
Improve environment and dependency management for node and researcher

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#927]
Fed-BioMed uses conda package manager to manage virtual environments and the packages for different components. The current implementation creates two distinct  environments for `node` and `researcher` where most of the packages are common. Additionally, the packages that are common should have the same version on both node and researcher to avoid regressions. 

The current approach with conda that is mentioned above has several drawbacks: 

-  Using different environments with conda that does not create lock file increases the risk of having incoherent packages on the researcher and node. And requires to declare versions in precisely in environment yml files. 
- Due to lack of lock file the environment that used by developers or users are not 100% same. Usually, that are differences in patches that are recently added. 
- Creates two environments that duplicates packages and increases the consumed during the installation of Fed-BioMed while using single environment is also possible. 

The solution can be migrating to different package manager or redesigning the package management of Fed-BioMed:

- Mamba: 
    - Much more faster than `conda`. It is `C++` implementation of conda that faster. 
    - No lock file generated. 
    - Support conda ecosystem
    - Possible to create virtual environments with binaries. 
      
- Poetry: 
    - Modern package manager for PyPi that facilitates reproducibility through lock files. 
    - Possible to add dependency groups such as dev, test etc. 
    - Creates virtual environments depending on Python version installed in the OS. 

- `pyproject.toml` : 
    -  native solution for packaging a python application. 
    - No lock file generated. Possible to add optional dependencies. 
    - Needs to be used with `venv` or other virtual env implementations. If `venv` is used the Python version of the virtual environment can not be controlled by Fed-BioMed installation (unless there is script that install required Python version for fedbiomed). 

Suggestions from @pandrey-fr, 
>  - package Fed-BioMed as an installable Python package using a pyproject.toml; enable its installation via pip (whether  "only" via Git, or by uploading releases on PyPI)
>   - write lightweight conda environments that install Fed-BioMed and its third-party binary dependencies, but not  python dependencies, that would be installed directly together with FBM

**IMPORTANT**:  While deciding to an implementation or a technology to manage dependencies it is important to keep in my mind that Fed-BioMed is a **framework** more than a python library.

**Comment by mvesin** [comment]
Also includes:
- consider creating a distinct `fedbiomed-unit-tests.yml` environment (was #877 )

**Comment by mvesin** [comment]
Notes from N.Niclausse investigation:
- conda => mamba: simple, tested, is faster
- using conda lock files (one per os) combined with .yaml: one option for management of dependencies; not only technical, need to define a workflow
- for packaging we could consider https://conda.github.io/conda-pack/

**Comment by mvesin** [comment]
See #1224 for implementing poetry + pip packages.
