### ISSUE TITLE
Setting `RESEARCHER_SERVER_HOST` env variable does not change server host in config file

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#946]
`RESEARCHER_SERVER_HOST` and `RESEACHER_SERVER_PORT` env variables  are not working properly for setting server host and port in configuration file. 

Please test:  

```
RESEARCHER_SERVER_HOST=123.123.123.123 ./scripts/fedbiomed_run configuration create -c researcher -f 
```

**Comment by clebreto** [comment]
In fedbiomed_environment script, the environment variable FEDBIOMED_NO_RESET controls whether the RESEARCHER_SERVER_HOST and others are unset.

The current way to have: 
`RESEARCHER_SERVER_HOST=123.123.123.123 ./scripts/fedbiomed_run configuration create -c researcher -f `
working, is to prefix it with FEDBIOMED_NO_RESET:
`FEDBIOMED_NO_RESET=1 RESEARCHER_SERVER_HOST=123.123.123.123 ./scripts/fedbiomed_run configuration create -c researcher -f `

**Comment by sharkovsky** [comment]
This sounds like it might be linked to #504
