### ISSUE TITLE
use pre-trained model

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#952]
As a user, I want to re-use a pre-trained model (eg transfer learning).

- [x] test use of pre-trained model weights (from another run of same Fed-BioMed notebook, from another Fed-BioMed notebook with same model to simulate import from non-Fed-BioMed training)
- [x] document in `User Guide > Researcher > Training Plan` ( )
  * don't create a new `notebooks/` entry
- [x] add export of trained model weights in existing notebooks
- [x] fix issue with `BaseTrainingPlan.export_model()` (see below)

**Comment by mvesin** [comment]
Report issue `BaseTrainingPlan.export_model()`:
- in a notebook, train your `exp` then save trained model with `exp.training_plan().export_model('/path/to/file')`
- stop notebook (in jupyter `Kernel > Restart Kernel and clear output of all cells`
- restart same notebook (or another notebook)
- instantiate your experiment (with `exp = Experiment(....)` line)
- load saved model with:
  ```
  exp.training_plan().import_model('/path/to/file')``
  ```
  or with:
  ```
  import torch
  model = torch.load('/path/to/file')
  ```
- it fails with error message:
  ```
  ModuleNotFoundError: No module named 'model_<a_unique_id_name>'
  ```

Explanation: 
- Fed-BioMed uses custom module name unique to each execution of a notebook for a training plan (thus model which is ofter defined as nested class of a training plan)
- more generally, the model class module and name of saved model may not match the one which is expected in Fed-BioMed (when doing `import_model()`) or in other software (when doing `export_model()`). So it's difficult to find a class name/module that would be good for any/most use.
- moreover, a common practice when sharing models is to know that we are using same model, so we don't need to export the model class, only the weights

Conclusion:
- proposed fix is to export/import **only the weights**, not the model class => adapt methods in training plan and `Model`
- note: this does not solve the caveat regarding pickle (you still need to trust the model weights provider as the `torch.load()` uses pickle which might execute arbitrary code if weights are sent by malicious attacker)
-

**Comment by ybouilla** [comment]
Re-opened issue because found an issue.

When editing directly `training_plan`, method `import_model`  fails because `model` within `training-plan` is not defined.

Example:

```pyhton

MyTrainingPlan(TorchTrainingPlan):
    ....

tp = MyTrainingPlan()

tp.import_model('/path/to/some/weights')  # this stanza fails

```

I think we are missing maybe a error message that says model has not been initialized or (more complicated) a way to load model

However, passing `training-plan` into `Experiment`  works:

```python
exp = Experiment()
exp.set_training_plan(MyTrainingPlan())

exp.training_plan().import_model('/path/to/my/weights') # this works
```

**Comment by mvesin** [comment]
Thank you @ybouilla , I also update labels and assigned to you (de-assign if you don't plan to investigate).

At least we need to:
- update `docs/user-guide/researcher/training-plan.md` that shows a `TrainingPlan().import_model()` which won't work
- we could add a security by checking `self._model` as you propose

We could stick to this for now.
Supporting use without experiment seems complicated as we made assumptions on the initialization of a training plan
For example we could expect this to work, but it doesn't
```
tp = MyTrainingPlan()
tp.post_init({}, TrainingArgs(), {})
tp.import_model()
```
So I would recommend not to try supporting this case (for now)

**Comment by sharkovsky** [comment]
Hi, a lot of this will be fixed after the refactoring of Experiment and Job, so please don't worry too much about it for now!

**Comment by mvesin** [comment]
Agree with @sharkovsky let's stick to the most simple fix.
