### ISSUE TITLE
Problems with VPN

### ISSUE THREAD

**Issue by alemolteni** [fedbiomed/fedbiomed#954]
I am trying to make fedbiomed work with the VPN by following the guide on the documentation. Everything worked fine both on node side and on server side, however, at this point I don't know how to start a training. 

For the node, I am using WSL and for the server I am using a virtual machine created with virtualbox (I am using bridged adapter, so the machine has a different IP address). I am connecting to this machine using ssh mapping the port on which jupyter runs to my localhost so that I can access the notebook from my browser with the command "ssh -L 8888:localhost:8888 myusername@ipaddress". 

If I try to use the bash launching the command stated on the guide on the server side and the analogous one on the node side, I get a connection refused network and I can't run the notebooks. If I don't use the bash then the researcher is not able to connect to the node. 

Can you please tell me what am I doing wrong? I really need to make fedbiomed work with the node being my computer and the researcher being a remote machine. Thanks in advance for your help

**Comment by alemolteni** [comment]
So basically I can't use notebooks with the VPN, but only scripts? Moreover I forgot to say that when I enter the bash on the node side I can't find anymore the folder with my datasets, I don't know if I am missing something. Thanks again

**Comment by mvesin** [comment]
Dear @alemolteni,

Thank you very much for using Fed-BioMed and giving feedback.

I suppose you are already familiar with launching Fed-BioMed without VPN ?
This might be helpful to start in a much simpler setup.

My answer is based on `v5.0.0` and documentation guide https://fedbiomed.org/latest/user-guide/deployment/deployment-vpn/
Please correct us if this is not the version and documentation you are using.
Sorry, I'm not sure to understand exactly where you have a failure, so I will recap a few steps.

You mention that everything works fine on server and node side.
Thus you should be able to successfully ping the VPN server from the node:

```
[user@node $] ${FEDBIOMED_DIR}/scripts/fedbiomed_vpn status node
** Checking docker VPN images & VPN access: node
- container node is running
- pinging VPN server from container node -> OK
```

If not, then your node and vpnserver/researcher components cannot communicate.
This might then be an infrastructure problem (independant of Fed-BioMed) in your WSL <=> virtualbox communications.

If node successfully pings vpnserver, then you are ready to setup FL training.
Let's give an example for `notebooks/101_getting-started.ipynb`

First, on the node side you need to share a dataset for the training, and start the node code, for example:
```
./scripts/fedbiomed_run node -am /data   ## load and share demo MNIST dataset
# start the node in background -- we plan to robustify this by launching as a service
nohup ./scripts/fedbiomed_run node start >./fedbiomed_node.out &
# follow output of running node
tail -f ./fedbiomed_node.out
```

Node should show some output (cf examples without using VPN) with final line:
```
2024-01-10 13:48:02,402 fedbiomed DEBUG - Sending new task request to researcher
```

Then on the researcher side, connect to the notebook and start executing the cells from the notebook.
When starting the experiment, it should be querying your node and finding the dataset with matching tags:
```
exp = Experiment(...)
...
2024-01-10 13:56:59,451 fedbiomed INFO - Starting researcher service...
2024-01-10 13:56:59,452 fedbiomed INFO - Waiting 3s for nodes to connect...
2024-01-10 13:57:01,084 fedbiomed DEBUG - Node: YOUR_NODE_ID polling for the tasks
2024-01-10 13:57:02,475 fedbiomed INFO - Node selected for training -> YOUR_NODE_ID
```

Then if you execute the cell with `exp.run()` in the notebook, the model trains with your node using the dataset on the node.

=> Can you confirm if this works ? If not, at which steps it fails with which error message ?

Then you mention launching the python script on the researcher instead of the notebook.
Before doing that, you need to **stop running the notebook** because it already has a communication (gRPC) server running on port 50051 (in Jupyter notebook interface, `Kernel > Restart Kernel`).

 If you launch the python script for the notebook while another server is running you'll get this error:

```
[user@server-container $] ipython ./notebooks/101_getting-started.py
...
E0110 14:59:10.174406647   26573 chttp2_server.cc:1063]                UNKNOWN:No address added out of total 2 resolved for 'localhost:50051' {created_time:"2024-01-10T14:59:10.174118305+01:00", children:[UNKNOWN:Unable to configure socket {fd:20, created_time:"2024-01-10T14:59:10.174090598+01:00", children:[UNKNOWN:Address already in use {created_time:"2024-01-10T14:59:10.174075682+01:00", errno:98, os_error:"Address already in use", syscall:"bind"}]}, UNKNOWN:Unable to configure socket {fd:20, created_time:"2024-01-10T14:59:10.174114043+01:00", children:[UNKNOWN:Address already in use {syscall:"bind", os_error:"Address already in use", errno:98, created_time:"2024-01-10T14:59:10.174111316+01:00"}]}]}
2024-01-10 14:59:10,174 fedbiomed ERROR - Researcher gRPC server has stopped. Please try to restart: Failed to bind to address localhost:50051; set GRPC_VERBOSITY=debug environment variable to see detailed error message.
```

In other words, you cannot run 2 Fed-BioMed researchers using the same network port at the same time (thus you cannot run one notebook and one script at the same time).

**Last minute**: sorry, it seems we introduced a regression in v5.0.0, as the notebooks are now only distributed a `.ipynb` so you need to convert it to `.py` to be able to run the script. We'll fix it in next version, sorry for that.

So you need to connect to the VPN researcher container with the user ID and run:
```
# note: conda complains with some errors (ModuleNotFoundError: No module named 'notebook.nbextensions')
# when doing this installation but still it installs jupyter extensions
[user@server-container $] conda install -c conda-forge 'jupyter_contrib_nbextensions~=0.7.0'
[user@server-container $] jupyter nbconvert --to script ./notebooks/101_getting-started.ipynb
```

Then you can launch the python script as mentioned above:

```
[user@server-container $] ipython ./notebooks/101_getting-started.py
...
## notebook runs fine and writes output
```

=> Does it help ? If not, can you precise which command you are launching and which error message you get ?
Thank you very much in advance.

**Comment by mvesin** [comment]
> So basically I can't use notebooks with the VPN, but only scripts?

You can use notebooks with the VPN:
- from the same machine connecting to `http://localhost:8888`
- or as you mention through ssh tunnel

What you cannot do is run simultaneously more than one Fed-BioMed `Experiment()`. Thus if you run a notebook, you cannot have a script or another notebook kernel already running.

> Moreover I forgot to say that when I enter the bash on the node side I can't find anymore the folder with my datasets, I don't know if I am missing something. Thanks again

When you are within the container on the node side (`[user@node-container]`), the directory `${FEDBIOMED_DIR}/envs/vpn/docker/node/run_mounts/data/` (where you can put your datasets for the node container) is mapped to `/data` so you should find your data here.

**Comment by mvesin** [comment]
> I have followed the commands that you have written (from the bash both in the node and in the server), everything works well in the node and I keep getting the message "Researcher server is not available, will retry connect in 2 seconds", but this happened even without the VPN so I think it is ok.

Yes, this will print this message until you reach the `exp = Experiment(...)` on researcher side.

> On the server side I tried to launch the command "./scripts/fedbiomed_run researcher start" however I can't connect via the ssh tunnel when I visit localhost:8888. I have also tried launching jupyter directly with the command "jupyter notebook --no-browser --port=8888" but still I can't connect to localhost:8888.

Thank you for clarifying.
When using containers/vpn, you don't have to launch the researcher. This is done automatically when starting the researcher container (`fedbiomed_vpn start researcher`). So you should be able to connect directly to `http://localhost:8888` (from the local machine, or the distant machine with your SSH tunnel).

You can check container logs to see if there was a problem launching researcher container:
```
[user@researcher $] cd envs/vpn/docker
[user@researcher $] docker compose logs researcher
```

> I am probably doing something wrong on the server side, I don't know if using a VPN using an ssh tunnel that maps the ports still works or not.

Using SSH tunnel is ok, we did this setup several times.

What is the error when connecting to `http://localhost:8888` ?

Can you test connecting from the local machine (the one where the researcher runs) to `http://localhost:8888` to check if the connectivity works or not ? (to separate if this is a Fed-BioMed researcher launch issue or a SSH tunneling issue) ?

> I believe all the commands should be launched inside the bash is it correct? I tried outside the bash and I connect to localhost:8888, but the server is not able to reach the client.

Yes, all commands for managing the researcher are launched inside the container (the bash).

But as mentioned before, you don't have to launch the researcher, this should be done by the researcher container.

**Comment by alemolteni** [comment]
I have tried to connect to localhost:8888 without launching the server and indeed it works, however I still can't launch a training. When I try to launch the cell in the notebook 101_getting-started where the experiment in created I get this output:

```
2024-01-11 14:21:22,646 fedbiomed INFO - Starting researcher service...
2024-01-11 14:21:22,647 fedbiomed INFO - Waiting 3s for nodes to connect...
2024-01-11 14:21:25,716 fedbiomed INFO - No nodes found, server will wait 17 more seconds until a node creates connection.
2024-01-11 14:21:43,794 fedbiomed WARNING - Server has not received connection from any remote nodes in MAX_GRPC_SERVER_SETUP_TIMEOUT: 20 This may effect the request created right after the server initialization. However, server will keep running in the background so you can retry the operations for sending requests to remote nodes until one receives.
2024-01-11 14:21:43,800 fedbiomed INFO - No available dataset has found in nodes with tags: ['#MNIST', '#dataset']
2024-01-11 14:21:43,807 fedbiomed DEBUG - Model file has been saved: /fedbiomed/var/experiments/Experiment_0008/model_18e562f8-e983-4a9c-9b3a-2945416dd1fe.py
Secure RNG turned off. This is perfectly fine for experimentation as it allows for much faster training performance, but remember to turn it on and retrain one last time before production with ``secure_mode`` turned on.
2024-01-11 14:21:43,824 fedbiomed DEBUG - using native torch optimizer
2024-01-11 14:21:43,827 fedbiomed INFO - Removing tensorboard logs from previous experiment
```
Is it possible that I have to increase the seconds the server waits for a connection? Thankyou again for your answer

**Comment by mvesin** [comment]
> I have tried to connect to localhost:8888 without launching the server and indeed it works

Congratulations, then you server (researcher) is now ready for training !

> ```
> 2024-01-11 14:21:22,646 fedbiomed INFO - Starting researcher service...
> 2024-01-11 14:21:22,647 fedbiomed INFO - Waiting 3s for nodes to connect...
> 2024-01-11 14:21:25,716 fedbiomed INFO - No nodes found, server will wait 17 more seconds until a node creates connection.
> 2024-01-11 14:21:43,794 fedbiomed WARNING - Server has not received connection from any remote nodes in MAX_GRPC_SERVER_SETUP_TIMEOUT: 20 This may effect the request created right after the server initialization. However, server will keep running in the background so you can retry the operations for sending requests to remote nodes until one receives.
> 2024-01-11 14:21:43,800 fedbiomed INFO - No available dataset has found in nodes with tags: ['#MNIST', '#dataset']
> 2024-01-11 14:21:43,807 fedbiomed DEBUG - Model file has been saved: /fedbiomed/var/experiments/Experiment_0008/model_18e562f8-e983-4a9c-9b3a-2945416dd1fe.py
> Secure RNG turned off. This is perfectly fine for experimentation as it allows for much faster training performance, but remember to turn it on and retrain one last time before production with ``secure_mode`` turned on.
> 2024-01-11 14:21:43,824 fedbiomed DEBUG - using native torch optimizer
> 2024-01-11 14:21:43,827 fedbiomed INFO - Removing tensorboard logs from previous experiment
> ```
> 
> Is it possible that I have to increase the seconds the server waits for a connection? Thankyou again for your answer

Thank you for reporting.
Then it means you have a node-researcher communication issue.
This is not a problem of server wait timeout, as a node retries every 2 seconds to connect to the researcher.

Can you confirm that your node is connected to your researcher via the VPN with the command below:

```
[user@node $] ${FEDBIOMED_DIR}/scripts/fedbiomed_vpn status node
** Checking docker VPN images & VPN access: node
- container node is running
- pinging VPN server from container node -> OK
```

Can you also confirm you launched the node inside the node's container ("the node bash") with the command below **before running the researcher notebook** and see the output below:

```
./scripts/fedbiomed_run node -am /data   ## load and share demo MNIST dataset
# start the node in background -- we plan to robustify this by launching as a service
nohup ./scripts/fedbiomed_run node start >./fedbiomed_node.out &
# follow output of running node
tail -f ./fedbiomed_node.out
```

Node should show some output (cf examples without using VPN) with final line:
```
2024-01-10 13:48:02,402 fedbiomed DEBUG - Sending new task request to researcher
```

If all these are OK then you have a functional node-researcher connection via VPN, a launched researcher and node.
If it still fails then something went wrong in the install process.
In that case, can you connect:
- to the node container (the bash) and `cat /fedbiomed/etc/config_node.ini`
- to the researcher container (the bash) and `cat /fedbiomed/etc/config_researcher.ini`

And share these output with us to check if the node-researcher addresses/port match.

By the way, if you wish more interactive support and have a Discord account, we can invite you to the Fed-BioMed Discord.
If you wish it, then please send an email to `fedbiomed-support@inria.fr` so we can invite you to Discord via email.

**Comment by alemolteni** [comment]
I can confirm the node is able to ping the server and that I launched the commands inside the node's container. I will share the outputs of those two commands:
`cat /fedbiomed/etc/config_node.ini`
```
[default]
id = NODE_57fbf558-a112-41df-b5d3-c063bf31d933
component = NODE
version = 2
db = ../var/db_NODE_57fbf558-a112-41df-b5d3-c063bf31d933.json

[mpspdz]
private_key = certs/cert_NODE_57fbf558-a112-41df-b5d3-c063bf31d933/MPSPDZ_certificate.key
public_key = certs/cert_NODE_57fbf558-a112-41df-b5d3-c063bf31d933/MPSPDZ_certificate.pem
mpspdz_ip = localhost
mpspdz_port = 14000
allow_default_biprimes = True
default_biprimes_dir = ../envs/common/default_biprimes

[security]
hashing_algorithm = SHA256
allow_default_training_plans = True
training_plan_approval = False
secure_aggregation = True
force_secure_aggregation = False

[researcher]
ip = localhost
port = 50051
```
```
[default]
id = RESEARCHER_2a29d023-023f-4eb0-b6fd-f8f1dafbaad7
component = RESEARCHER
version = 2
db = ../var/db_RESEARCHER_2a29d023-023f-4eb0-b6fd-f8f1dafbaad7.json

[mpspdz]
private_key = certs/cert_RESEARCHER_2a29d023-023f-4eb0-b6fd-f8f1dafbaad7/MPSPDZ_certificate.key
public_key = certs/cert_RESEARCHER_2a29d023-023f-4eb0-b6fd-f8f1dafbaad7/MPSPDZ_certificate.pem
mpspdz_ip = 10.222.0.2
mpspdz_port = 14000
allow_default_biprimes = True
default_biprimes_dir = ../envs/common/default_biprimes

[server]
host = 10.222.0.2
port = 50051
pem = certs/cert_RESEARCHER_2a29d023-023f-4eb0-b6fd-f8f1dafbaad7/server_certificate.pem
key = certs/cert_RESEARCHER_2a29d023-023f-4eb0-b6fd-f8f1dafbaad7/server_certificate.key
```

I will gladly send email and join your discord server, thankyou again for your answer

**Comment by mvesin** [comment]
Thank you very much for these details:

> I can confirm the node is able to ping the server and that I launched the commands inside the node's container. I will share the outputs of those two commands: `cat /fedbiomed/etc/config_node.ini`
> 
...
> [researcher]
> ip = localhost
> port = 50051
> ```

This is where the issue stands !
It should not happen when running a node in a container.
This is weird because node configuration in node container is not generated this way.

There you should have:

```
[server]
host = 10.222.0.2
port = 50051
```

Are you really running your node **inside the container** (and also running this `cat` command inside the container) ?

I mean, connect to the node, then launch the node:

```
[user@node $] cd ${FEDBIOMED_DIR}/envs/vpn/docker
[user@node $] docker compose exec -u $(id -u) node bash -ci 'export PYTHONPATH=/fedbiomed && export FEDBIOMED_NO_RESET=1 && eval "$(conda shell.bash hook)" && conda activate fedbiomed-node && bash'
[user@node-container $] nohup ./scripts/fedbiomed_run node start >./fedbiomed_node.out &
```

If yes, you just need edit the `/fedbiomed/etc/config_node.ini` file and fix the host address as shown abouve, then stop / restart the node (command `nohup ./scripts/fedbiomed_run node start`).

Does it solve the issue ?

BTW, why did this happen ?
The first configuration with the command below generates the node configuration.
So probably something went wrong at this step.

```
[user@node $] docker compose exec -u $(id -u) node bash -ci 'export FORCE_SECURE_AGGREGATION='${FORCE_SECURE_AGGREGATION}'&& export MPSPDZ_IP=$VPN_IP && export MPSPDZ_PORT=14001 && export RESEARCHER_SERVER_HOST=10.222.0.2 && export RESEARCHER_SERVER_PORT=50051 && export PYTHONPATH=/fedbiomed && export FEDBIOMED_NO_RESET=1 && ENABLE_TRAINING_PLAN_APPROVAL=True ALLOW_DEFAULT_TRAINING_PLANS=True ./scripts/fedbiomed_run environ-node configuration create --component NODE --use-current'
```

**Comment by alemolteni** [comment]
I modified the file and now it worked, I succesfully managed to start the 101-getting_started notebook. Thankyou very much for your help. I have a couple of last questions. When I turn off and on the computer I do the following steps:

- clean running containers, containers files, temporary files both on nodeside and on server side
- `[user@server $] ${FEDBIOMED_DIR}/scripts/fedbiomed_vpn configure researcher`
- `[user@server $] ${FEDBIOMED_DIR}/scripts/fedbiomed_vpn start researcher`
- `[user@server $] docker compose exec vpnserver bash -ci 'python ./vpn/bin/configure_peer.py genconf node NODETAG'`
- send config.env to the node
- `[user@node $] docker compose up -d node`
- `[user@node $] docker compose exec node wg show wg0 public-key | tr -d '\r' >/tmp/publickey-nodeside`
- send public key to the server
- `[user@server $] docker compose exec vpnserver bash -ci "python ./vpn/bin/configure_peer.py add node NODETAG $(cat /tmp/publickey-serverside)"`
- `[user@node $] docker compose exec -u $(id -u) node bash -ci 'export FORCE_SECURE_AGGREGATION='${FORCE_SECURE_AGGREGATION}'&& export MPSPDZ_IP=$VPN_IP && export MPSPDZ_PORT=14001 && export RESEARCHER_SERVER_HOST=10.222.0.2 && export RESEARCHER_SERVER_PORT=50051 && export PYTHONPATH=/fedbiomed && export FEDBIOMED_NO_RESET=1 && ENABLE_TRAINING_PLAN_APPROVAL=True ALLOW_DEFAULT_TRAINING_PLANS=True ./scripts/fedbiomed_run environ-node configuration create --component NODE --use-current'`

With these steps everything works fine, but I was wondering if it is necessary to recreate the config.env file and the public key.

Secondly, I copied my data inside the /notebooks/data folder, however when I use the command to add data to a node and I insert the path to that folder I get this message
```
Traceback (most recent call last):
  File "/fedbiomed/fedbiomed/node/cli_utils/_io.py", line 110, in validated_path_input
    assert os.path.isdir(path)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alem/.conda/envs/fedbiomed-node/lib/python3.10/tkinter/messagebox.py", line 76, in _show
    res = Message(**options).show()
  File "/home/alem/.conda/envs/fedbiomed-node/lib/python3.10/tkinter/commondialog.py", line 42, in show
    master = _get_temp_root()
  File "/home/alem/.conda/envs/fedbiomed-node/lib/python3.10/tkinter/__init__.py", line 306, in _get_temp_root
    raise RuntimeError("No master specified and tkinter is "
RuntimeError: No master specified and tkinter is configured to not support default root
```
Moreover I went to the folder `/envs/vpn/docker/node/run_mounts/data/` inside the node container, but the folder is empty. Do you have any idea what am I doing wrong? Thankyou

**Comment by mvesin** [comment]
> I modified the file and now it worked, I succesfully managed to start the 101-getting_started notebook. 

Great news, congrats !

>Thankyou very much for your help. I have a couple of last questions. When I turn off and on the computer I do the following steps:
> 
>     * clean running containers, containers files, temporary files both on nodeside and on server side
...
> 
> With these steps everything works fine, but I was wondering if it is necessary to recreate the config.env file and the public key.

Basically with these steps what you are doing each time you stop your computer is:
- clean out (delete) you Fed-BioMed instance
- when reconnecting, redo the setup of a new Fed-BioMed (FB) instance from scratch

This is perfectly valid, but maybe not what you want to do (stop your FB instance, then restart it when restarting your computer). You probably want a "long lived" FB instance that can be relaunched across reboots.
(this is the main use case we envisioned)

Once you did the initial installation of a FB instance, you can manage it as "normal" docker containers (classical docker
commands and lifecycle).
If you installed docker with default configuration, it will stop your containers when you stop your machine,
and then restart your researcher and node containers when restarting the machine (in a real life deployment
they are on servers so this does not happen that often).

So after rebooting the machine you just need to:
- use the researcher: https://fedbiomed.org/latest/user-guide/deployment/deployment-vpn/#use-the-server
  (nothing to do as it is started automatically by the docker container => just connect to the localhost:8888 )
- use the node: https://fedbiomed.org/latest/user-guide/deployment/deployment-vpn/#use-the-node
  (you still have to connect to the container and launch the node with `nohup fedbiomed_run node start` command
  We plan to improve that part in future release)

You can also stop/start the docker containers at any time if needed for maintenance, see misc server/node commands:
https://fedbiomed.org/latest/user-guide/deployment/deployment-vpn/#misc-server-management-commands

Hope it clarifies it ?

> Secondly, I copied my data inside the /notebooks/data folder, however when I use the command to add data to a node and I insert the path to that folder I get this message
> 
> ```
> Traceback (most recent call last):
>   File "/fedbiomed/fedbiomed/node/cli_utils/_io.py", line 110, in validated_path_input
>     assert os.path.isdir(path)
> AssertionError
> 
...
> Moreover I went to the folder `/envs/vpn/docker/node/run_mounts/data/` inside the node container, but the folder is empty. Do you have any idea what am I doing wrong? Thankyou

This part is a little bit tricky if you're not that familiar with docker.
Some path from your laptop are mapped to other path inside the docker container.
The path to `/envs/vpn/docker/node/run_mounts/data/` on your laptop is mapped to `/data`.

You can check the full docker configuration here: https://github.com/fedbiomed/fedbiomed/blob/master/envs/vpn/docker/docker-compose.yml

So when adding data to your node the simple way might be to:
- from **outside** the container: put data in `/envs/vpn/docker/node/run_mounts/data/MYFILE`
- from **inside** the container: run `fedbiomed_run node add` and pick `/data/MYFILE` path (or run the node GUI to do that)

Does it solve the issue ?

---

As a closing remark: the VPN+container mode does not change the Fed-BioMed library.
It just wraps and packages Fed-BioMed in docker containers, connected one to another with
a WireGuard VPN, and uses parameters (environment variables) targeted towards a secure development.

This is meant to help the user for real life deployments (though we plan to improve it and make it simpler).

But it is perfectly possible to build your own secure deployment with firewalls, VPN, secured hosts around
the Fed-BioMed library if this seems a better option or simpler to you.

**Comment by mvesin** [comment]
Hello,

Is it now solved for you or do you have additional questions ?

**Comment by alemolteni** [comment]
Hi sorry for the absence, I am done with the questions, thankyou very much for your support and your answers
