### ISSUE TITLE
No module named 'notebook.base' error when running jupyter nbconvert

### ISSUE THREAD

**Issue by ErwanDemairy** [fedbiomed/fedbiomed#957]
When installing from scratch the fedbiomed-researcher conda environment, the version of `notebook` package is set to > 7.0.0, making fail any `jupyter nbconvert` with the error message : `No module named 'notebook.base'`
1. this problem does not always appear on old insallations since `notebook` is a dependency that is not required to be udpated (but using the `--update-deps` in the `conda update` command would force the conda environments to be consistent for old and new installations).
2. downgrading notebook to 6.*.* solves the issue.

**Comment by mvesin** [comment]
hi Erwan, isnt this part of PR #937 /  issue #935 ?

**Comment by mvesin** [comment]
Fixed in #931 by @ErwanDemairy

**Comment by ErwanDemairy** [comment]
Solved by #931
