### ISSUE TITLE
`KeyError` when loading breakpoint with Scaffold

### ISSUE THREAD

**Issue by sharkovsky** [fedbiomed/fedbiomed#977]
To reproduce:
1) run one round of experiment using the `Scaffold` aggregator, save the breakpoint
2) load the breakpoint
3) run another round

In the aggregation step, after loading the breakpoint, the `nodes_states` member of the Scaffold instance is empty, and fails with a `KeyError`. The traceback, in my example, is:
```
--------------------
Fed-BioMed researcher stopped due to unknown error:
'NODE_bc093f51-7aad-4b27-b961-826db51970e8'
More details in the backtrace extract below
--------------------
Traceback (most recent call last):
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/researcher/experiment.py", line 76, in payload
    ret = function(*args, **kwargs)
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/researcher/experiment.py", line 1514, in run_once
    aggregated_params = self._aggregator.aggregate(model_params,
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/researcher/aggregators/scaffold.py", line 188, in aggregate
    self.update_correction_states(model_updates, n_updates)
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/researcher/aggregators/scaffold.py", line 249, in update_correction_states
    self.nodes_states[node_id].update(
KeyError: 'NODE_bc093f51-7aad-4b27-b961-826db51970e8'
```

**Comment by mvesin** [comment]
I can confirm the same issue using:
- `develop` branch
- `general-breakpoint-save-resume.ipynb`, changing the `Experiment(... aggregator=Scaffold())` and then adding `from fedbiomed.researcher.aggregators import Scaffold`
- proceeding as you describe

Maybe @ybouilla has a clue ?

**Comment by mvesin** [comment]
hi @ybouilla there seems to be missing items in the `save_breakpoint() / load_breakpoint()` for `Scaffold`

**Comment by ybouilla** [comment]
Hi all, thanks for using Fed-BioMed and reporting this issue! 
I could reproduce this error from the master branch too

**Comment by ybouilla** [comment]
Started working for a fix on branch #hotfix/977-fix-native-scaffold-breakpoints
